// PAPER PLANET — GENERATED by tools/measure-assets.mjs. Do not edit by hand.
//
// What every shipped file actually measures, so the mix in ./mix.ts can be
// written as targets rather than as guessed numbers. All figures are ITU-R
// BS.1770-4 K-weighted, taken from the mono file — the graph's mono-to-stereo
// upmix adds the same +3 LU to every one of them, so it cancels in every
// comparison the mix makes.
//
//   l100  loudest 100 ms window. The statistic for one-shots: a crease snap is
//         40 ms of event inside a one-second file, and the standard 400 ms
//         window reads it 5-8 LU quieter than it sounds.
//   li    gated integrated loudness. The statistic for a bed you live with.
//   ls    loudest 3 s window — a bed's loudest sustained passage.
//   lu    ungated K-weighted level of the whole file. The statistic for a
//         granular source, where a grain lands anywhere with equal chance.
//   tp    true peak, 4x oversampled, dBTP.

/** Measured level of one shipped file. Every figure is dB or LUFS. */
export interface MeasuredLevel {
  readonly l100: number
  readonly li: number
  readonly ls: number
  readonly lu: number
  readonly tp: number
}

export const LEVELS: Readonly<Record<string, MeasuredLevel>> = {
  '/audio/alive-breath-1.mp3': { l100: -15.16, li: -20.19, ls: -23.64, lu: -21.43, tp: -5.88 },
  '/audio/alive-breath-2.mp3': { l100: -14.94, li: -20.63, ls: -24.06, lu: -21.85, tp: -4.84 },
  '/audio/alive-happy-1.mp3': { l100: -16.91, li: -24.28, ls: -30.07, lu: -26.79, tp: -11.95 },
  '/audio/alive-happy-2.mp3': { l100: -16.95, li: -26.18, ls: -30.56, lu: -27.28, tp: -11.7 },
  '/audio/alive-nuzzle-1.mp3': { l100: -14.95, li: -20.68, ls: -25.32, lu: -21.44, tp: -3.17 },
  '/audio/alive-nuzzle-2.mp3': { l100: -17.4, li: -20.47, ls: -24.95, lu: -21.07, tp: -5.69 },
  '/audio/amb-meadow.mp3': { l100: -23.55, li: -27.57, ls: -26.76, lu: -27.57, tp: -11.71 },
  '/audio/amb-night.mp3': { l100: -19.39, li: -24.72, ls: -22.14, lu: -24.78, tp: -10.4 },
  '/audio/amb-rain.mp3': { l100: -19.3, li: -25.58, ls: -24.57, lu: -25.58, tp: -6.66 },
  '/audio/amb-shore.mp3': { l100: -18.49, li: -27.34, ls: -25.73, lu: -28.5, tp: -7.96 },
  '/audio/amb-tearoom.mp3': { l100: -17.97, li: -30.49, ls: -26.94, lu: -33.28, tp: -5.94 },
  '/audio/crease-crisp-1.mp3': { l100: -18.17, li: -23, ls: -31.75, lu: -23.94, tp: -1.14 },
  '/audio/crease-crisp-2.mp3': { l100: -23.34, li: -28.66, ls: -37.41, lu: -28.57, tp: -1.74 },
  '/audio/crease-crisp-3.mp3': { l100: -23.03, li: -29.05, ls: -37.71, lu: -30.12, tp: -1.58 },
  '/audio/crease-crisp-4.mp3': { l100: -20.93, li: -26.93, ls: -35.68, lu: -25.08, tp: -1.49 },
  '/audio/crease-set-1.mp3': { l100: -18.43, li: -24.44, ls: -31.32, lu: -26.74, tp: -4.93 },
  '/audio/crease-set-2.mp3': { l100: -17.41, li: -24.94, ls: -31.76, lu: -27.18, tp: -5.73 },
  '/audio/crease-soft-1.mp3': { l100: -14.68, li: -19.42, ls: -25.06, lu: -20.48, tp: -1.63 },
  '/audio/crease-soft-2.mp3': { l100: -17.35, li: -21.87, ls: -28.46, lu: -23.54, tp: -1.76 },
  '/audio/crease-soft-3.mp3': { l100: -15.62, li: -19.42, ls: -25.01, lu: -20.43, tp: -1.99 },
  '/audio/crease-soft-4.mp3': { l100: -16.53, li: -19.8, ls: -25.77, lu: -20.85, tp: -1.89 },
  '/audio/fold-mountain-1.mp3': { l100: -16.05, li: -20.95, ls: -27.24, lu: -22.08, tp: -1.83 },
  '/audio/fold-mountain-2.mp3': { l100: -15.99, li: -23.17, ls: -29.12, lu: -24.54, tp: -1.79 },
  '/audio/fold-mountain-3.mp3': { l100: -18.07, li: -24.61, ls: -30.06, lu: -25.79, tp: -1.67 },
  '/audio/fold-petal-1.mp3': { l100: -17.46, li: -25.32, ls: -29.9, lu: -25.73, tp: -1.61 },
  '/audio/fold-petal-2.mp3': { l100: -21.51, li: -30.85, ls: -34.28, lu: -29.8, tp: -1.88 },
  '/audio/fold-reverse-1.mp3': { l100: -20.92, li: -28.18, ls: -34.07, lu: -29.27, tp: -1.71 },
  '/audio/fold-reverse-2.mp3': { l100: -21.63, li: -26.9, ls: -32.69, lu: -28.53, tp: -1.82 },
  '/audio/fold-squash-1.mp3': { l100: -14.38, li: -20.74, ls: -25.11, lu: -20.64, tp: -1.13 },
  '/audio/fold-squash-2.mp3': { l100: -19.1, li: -28.02, ls: -31.43, lu: -27.46, tp: -1.72 },
  '/audio/fold-valley-1.mp3': { l100: -19.62, li: -23.79, ls: -29.22, lu: -24.53, tp: -1.64 },
  '/audio/fold-valley-2.mp3': { l100: -18.79, li: -24.16, ls: -29.99, lu: -25.52, tp: -1.83 },
  '/audio/fold-valley-3.mp3': { l100: -13.77, li: -19.54, ls: -24.55, lu: -20.18, tp: -1.74 },
  '/audio/press-flatten-1.mp3': { l100: -15.98, li: -20.62, ls: -27.95, lu: -22.66, tp: -1.57 },
  '/audio/press-flatten-2.mp3': { l100: -19.76, li: -24.47, ls: -29.15, lu: -24.98, tp: -1.7 },
  '/audio/press-release-1.mp3': { l100: -16.92, li: -21.39, ls: -28.01, lu: -23.54, tp: -1.48 },
  '/audio/press-release-2.mp3': { l100: -17.3, li: -22.04, ls: -27.62, lu: -22.82, tp: -0.91 },
  '/audio/reward-goldleaf-1.mp3': { l100: -18.42, li: -23.58, ls: -27.33, lu: -24.72, tp: -0.48 },
  '/audio/reward-goldleaf-2.mp3': { l100: -16.66, li: -21.46, ls: -25.06, lu: -22.31, tp: -0.83 },
  '/audio/reward-mastery.mp3': { l100: -13.68, li: -21.62, ls: -23.88, lu: -23.24, tp: -6.47 },
  '/audio/reward-sheets-1.mp3': { l100: -14.28, li: -20.5, ls: -25.82, lu: -22.13, tp: -1.51 },
  '/audio/reward-sheets-2.mp3': { l100: -13.13, li: -19.53, ls: -24.37, lu: -20.2, tp: -1.78 },
  '/audio/reward-unlock.mp3': { l100: -17.04, li: -24.96, ls: -29.04, lu: -24.34, tp: -1.94 },
  '/audio/sheet-flip-1.mp3': { l100: -13.93, li: -21.54, ls: -27.98, lu: -22.69, tp: -2.01 },
  '/audio/sheet-flip-2.mp3': { l100: -14.87, li: -19.94, ls: -27.98, lu: -22.15, tp: -2.15 },
  '/audio/sheet-flip-3.mp3': { l100: -18.03, li: -25.08, ls: -31.93, lu: -27.01, tp: -1.98 },
  '/audio/sheet-lift-1.mp3': { l100: -14.21, li: -21.06, ls: -26.77, lu: -22.08, tp: -5.61 },
  '/audio/sheet-lift-2.mp3': { l100: -15.66, li: -21.29, ls: -27.34, lu: -22.76, tp: -1.73 },
  '/audio/sheet-pickup-1.mp3': { l100: -16.14, li: -24.88, ls: -28.72, lu: -23.8, tp: -1.88 },
  '/audio/sheet-pickup-2.mp3': { l100: -16, li: -21.84, ls: -30.49, lu: -25.07, tp: -2.02 },
  '/audio/sheet-settle-1.mp3': { l100: -15.86, li: -22.67, ls: -29.25, lu: -25.55, tp: -2.88 },
  '/audio/sheet-settle-2.mp3': { l100: -14.36, li: -21.68, ls: -28.22, lu: -24.15, tp: -3.51 },
  '/audio/sheet-settle-3.mp3': { l100: -13.76, li: -22.71, ls: -26.5, lu: -22.43, tp: -2.5 },
  '/audio/sheet-slide-1.mp3': { l100: -15.7, li: -18.88, ls: -24.38, lu: -20.21, tp: -6.46 },
  '/audio/sheet-slide-2.mp3': { l100: -16.32, li: -18.95, ls: -24.45, lu: -20.08, tp: -6.17 },
  '/audio/sheet-slide-3.mp3': { l100: -15.41, li: -18.57, ls: -24.67, lu: -19.98, tp: -6.73 },
  '/audio/sheet-slide-4.mp3': { l100: -16.12, li: -18.17, ls: -24.47, lu: -19.67, tp: -7.97 },
  '/audio/texture-burnish.mp3': { l100: -20.84, li: -28.09, ls: -26.27, lu: -28.21, tp: -1.51 },
  '/audio/texture-press-hold.mp3': { l100: -17.09, li: -26.89, ls: -25.15, lu: -27.1, tp: -1.22 },
  '/audio/texture-rub-fast.mp3': { l100: -9.36, li: -19.52, ls: -17.43, lu: -19.69, tp: -1.25 },
  '/audio/texture-rub-slow.mp3': { l100: -12.46, li: -20.42, ls: -18.2, lu: -20.49, tp: -1.26 },
  '/audio/ui-back-1.mp3': { l100: -19.33, li: -21.68, ls: -30, lu: -22.62, tp: -4.14 },
  '/audio/ui-back-2.mp3': { l100: -16.43, li: -24.25, ls: -29.87, lu: -23.25, tp: -0.47 },
  '/audio/ui-close-1.mp3': { l100: -26.06, li: -32.08, ls: -40.83, lu: -28.68, tp: -4.16 },
  '/audio/ui-close-2.mp3': { l100: -25.7, li: -31.72, ls: -40.47, lu: -26.86, tp: -6.89 },
  '/audio/ui-confirm-1.mp3': { l100: -18.36, li: -26.06, ls: -31.74, lu: -27.16, tp: -12.06 },
  '/audio/ui-confirm-2.mp3': { l100: -18.67, li: -27.42, ls: -32.01, lu: -27.43, tp: -11.63 },
  '/audio/ui-open-1.mp3': { l100: -18.4, li: -23.85, ls: -31.05, lu: -25.5, tp: -1.75 },
  '/audio/ui-open-2.mp3': { l100: -17.86, li: -23.15, ls: -28.87, lu: -23.58, tp: -1.96 },
  '/audio/ui-tap-1.mp3': { l100: -28.62, li: -34.64, ls: -43.39, lu: -32.33, tp: -7.99 },
  '/audio/ui-tap-2.mp3': { l100: -29.08, li: -35.1, ls: -43.85, lu: -32.79, tp: -11.69 },
  '/audio/ui-tap-3.mp3': { l100: -27.65, li: -33.67, ls: -42.43, lu: -28.81, tp: -3.67 },
  '/audio/ui-tap-4.mp3': { l100: -26.7, li: -32.72, ls: -41.47, lu: -29.9, tp: -5.59 },
  '/audio/ui-toggle-1.mp3': { l100: -25.25, li: -31.27, ls: -40.03, lu: -26.41, tp: -4.9 },
  '/audio/ui-toggle-2.mp3': { l100: -25.17, li: -31.19, ls: -39.94, lu: -29.34, tp: -4.49 },
}
