// PAPER PLANET — GENERATED by tools/gen-sfx.mjs. Do not edit by hand.
//
// Every asset is close-mic'd paper generated with ElevenLabs, then mastered:
// DC-removed, high-passed, silence-trimmed, loudness-matched per family and
// peak-limited. Loops are tail-over-head crossfaded so they wrap seamlessly.

import type { SfxCue, AmbienceId } from '../contracts'

/** One playable file. `duration` is the mastered length in seconds. */
export interface AudioAsset {
  readonly file: string
  readonly bytes: number
  readonly duration: number
  readonly peakDb: number
  readonly rmsDb: number
}

/** A continuous source built to wrap; `loopEnd` is its seamless length. */
export interface LoopAsset extends AudioAsset {
  readonly loopEnd: number
}

/** Continuous sources the granular friction voice and press-hold layer play. */
export type TextureId = 'texture.rub.slow' | 'texture.rub.fast' | 'texture.burnish' | 'texture.press.hold'

/** Round-robin variants per cue. Index 0 is always present. */
export const SFX: Readonly<Record<SfxCue, readonly AudioAsset[]>> = {
  'crease.soft': [
    { file: '/audio/crease-soft-1.mp3', bytes: 16718, duration: 1.045, peakDb: -1.7, rmsDb: -21.8 },
    { file: '/audio/crease-soft-2.mp3', bytes: 15464, duration: 0.967, peakDb: -1.8, rmsDb: -23.6 },
    { file: '/audio/crease-soft-3.mp3', bytes: 16718, duration: 1.045, peakDb: -2, rmsDb: -21.6 },
    { file: '/audio/crease-soft-4.mp3', bytes: 15464, duration: 0.967, peakDb: -1.9, rmsDb: -22.5 },
  ],
  'crease.crisp': [
    { file: '/audio/crease-crisp-1.mp3', bytes: 7941, duration: 0.496, peakDb: -1.2, rmsDb: -22.1 },
    { file: '/audio/crease-crisp-2.mp3', bytes: 6269, duration: 0.392, peakDb: -1.9, rmsDb: -23.3 },
    { file: '/audio/crease-crisp-3.mp3', bytes: 8359, duration: 0.522, peakDb: -1.9, rmsDb: -23.3 },
    { file: '/audio/crease-crisp-4.mp3', bytes: 4179, duration: 0.261, peakDb: -1.5, rmsDb: -21.7 },
  ],
  'crease.set': [
    { file: '/audio/crease-set-1.mp3', bytes: 16718, duration: 1.045, peakDb: -4.9, rmsDb: -22 },
    { file: '/audio/crease-set-2.mp3', bytes: 16718, duration: 1.045, peakDb: -5.8, rmsDb: -21.2 },
  ],
  'fold.valley': [
    { file: '/audio/fold-valley-1.mp3', bytes: 16300, duration: 1.019, peakDb: -1.8, rmsDb: -26.1 },
    { file: '/audio/fold-valley-2.mp3', bytes: 17136, duration: 1.071, peakDb: -1.8, rmsDb: -26.7 },
    { file: '/audio/fold-valley-3.mp3', bytes: 17554, duration: 1.097, peakDb: -1.8, rmsDb: -21.9 },
  ],
  'fold.mountain': [
    { file: '/audio/fold-mountain-1.mp3', bytes: 14628, duration: 0.914, peakDb: -1.9, rmsDb: -22.5 },
    { file: '/audio/fold-mountain-2.mp3', bytes: 16718, duration: 1.045, peakDb: -1.8, rmsDb: -24.8 },
    { file: '/audio/fold-mountain-3.mp3', bytes: 17972, duration: 1.123, peakDb: -1.7, rmsDb: -25.8 },
  ],
  'fold.reverse': [
    { file: '/audio/fold-reverse-1.mp3', bytes: 15882, duration: 0.993, peakDb: -1.8, rmsDb: -27.4 },
    { file: '/audio/fold-reverse-2.mp3', bytes: 18390, duration: 1.149, peakDb: -1.9, rmsDb: -27 },
  ],
  'fold.petal': [
    { file: '/audio/fold-petal-1.mp3', bytes: 18390, duration: 1.149, peakDb: -1.6, rmsDb: -25.1 },
    { file: '/audio/fold-petal-2.mp3', bytes: 17136, duration: 1.071, peakDb: -2.1, rmsDb: -26.5 },
  ],
  'fold.squash': [
    { file: '/audio/fold-squash-1.mp3', bytes: 17136, duration: 1.071, peakDb: -1.4, rmsDb: -22.2 },
    { file: '/audio/fold-squash-2.mp3', bytes: 19226, duration: 1.202, peakDb: -1.7, rmsDb: -27.7 },
  ],
  'sheet.slide': [
    { file: '/audio/sheet-slide-1.mp3', bytes: 18390, duration: 1.149, peakDb: -6.8, rmsDb: -22.4 },
    { file: '/audio/sheet-slide-2.mp3', bytes: 17554, duration: 1.097, peakDb: -6.2, rmsDb: -22.4 },
    { file: '/audio/sheet-slide-3.mp3', bytes: 16300, duration: 1.019, peakDb: -7.6, rmsDb: -22.6 },
    { file: '/audio/sheet-slide-4.mp3', bytes: 15882, duration: 0.993, peakDb: -8.5, rmsDb: -22.4 },
  ],
  'sheet.flip': [
    { file: '/audio/sheet-flip-1.mp3', bytes: 14210, duration: 0.888, peakDb: -2, rmsDb: -23.1 },
    { file: '/audio/sheet-flip-2.mp3', bytes: 12538, duration: 0.784, peakDb: -2.1, rmsDb: -22.8 },
    { file: '/audio/sheet-flip-3.mp3', bytes: 15464, duration: 0.967, peakDb: -2, rmsDb: -24.5 },
  ],
  'sheet.lift': [
    { file: '/audio/sheet-lift-1.mp3', bytes: 16300, duration: 1.019, peakDb: -5.6, rmsDb: -22.7 },
    { file: '/audio/sheet-lift-2.mp3', bytes: 16718, duration: 1.045, peakDb: -1.7, rmsDb: -22.7 },
  ],
  'sheet.settle': [
    { file: '/audio/sheet-settle-1.mp3', bytes: 20480, duration: 1.28, peakDb: -2.9, rmsDb: -22.4 },
    { file: '/audio/sheet-settle-2.mp3', bytes: 18808, duration: 1.176, peakDb: -3.5, rmsDb: -22.6 },
    { file: '/audio/sheet-settle-3.mp3', bytes: 18808, duration: 1.176, peakDb: -2.5, rmsDb: -22.7 },
  ],
  'sheet.pickup': [
    { file: '/audio/sheet-pickup-1.mp3', bytes: 15464, duration: 0.967, peakDb: -1.9, rmsDb: -24.9 },
    { file: '/audio/sheet-pickup-2.mp3', bytes: 13792, duration: 0.862, peakDb: -2, rmsDb: -22.1 },
  ],
  'press.flatten': [
    { file: '/audio/press-flatten-1.mp3', bytes: 14210, duration: 0.888, peakDb: -1.6, rmsDb: -21.7 },
    { file: '/audio/press-flatten-2.mp3', bytes: 18390, duration: 1.149, peakDb: -1.7, rmsDb: -24.3 },
  ],
  'press.release': [
    { file: '/audio/press-release-1.mp3', bytes: 17136, duration: 1.071, peakDb: -1.5, rmsDb: -23.7 },
    { file: '/audio/press-release-2.mp3', bytes: 15882, duration: 0.993, peakDb: -1.6, rmsDb: -24.1 },
  ],
  'ui.tap': [
    { file: '/audio/ui-tap-1.mp3', bytes: 3761, duration: 0.235, peakDb: -8.2, rmsDb: -26.2 },
    { file: '/audio/ui-tap-2.mp3', bytes: 3761, duration: 0.235, peakDb: -11.7, rmsDb: -24.4 },
    { file: '/audio/ui-tap-3.mp3', bytes: 2089, duration: 0.131, peakDb: -3.7, rmsDb: -24.4 },
    { file: '/audio/ui-tap-4.mp3', bytes: 3343, duration: 0.209, peakDb: -5.8, rmsDb: -24.2 },
  ],
  'ui.back': [
    { file: '/audio/ui-back-1.mp3', bytes: 8777, duration: 0.549, peakDb: -4.2, rmsDb: -24.2 },
    { file: '/audio/ui-back-2.mp3', bytes: 10449, duration: 0.653, peakDb: -0.9, rmsDb: -25.4 },
  ],
  'ui.confirm': [
    { file: '/audio/ui-confirm-1.mp3', bytes: 16718, duration: 1.045, peakDb: -12.1, rmsDb: -24.3 },
    { file: '/audio/ui-confirm-2.mp3', bytes: 16718, duration: 1.045, peakDb: -11.6, rmsDb: -24.4 },
  ],
  'ui.open': [
    { file: '/audio/ui-open-1.mp3', bytes: 13374, duration: 0.836, peakDb: -1.7, rmsDb: -25.3 },
    { file: '/audio/ui-open-2.mp3', bytes: 14210, duration: 0.888, peakDb: -2, rmsDb: -25 },
  ],
  'ui.close': [
    { file: '/audio/ui-close-1.mp3', bytes: 2925, duration: 0.183, peakDb: -4.2, rmsDb: -26.1 },
    { file: '/audio/ui-close-2.mp3', bytes: 2089, duration: 0.131, peakDb: -7, rmsDb: -26.1 },
  ],
  'ui.toggle': [
    { file: '/audio/ui-toggle-1.mp3', bytes: 2089, duration: 0.131, peakDb: -5, rmsDb: -24.5 },
    { file: '/audio/ui-toggle-2.mp3', bytes: 4179, duration: 0.261, peakDb: -4.8, rmsDb: -21.5 },
  ],
  'alive.breath': [
    { file: '/audio/alive-breath-1.mp3', bytes: 28839, duration: 1.802, peakDb: -5.9, rmsDb: -23.5 },
    { file: '/audio/alive-breath-2.mp3', bytes: 28839, duration: 1.802, peakDb: -5.3, rmsDb: -23.4 },
  ],
  'alive.happy': [
    { file: '/audio/alive-happy-1.mp3', bytes: 22569, duration: 1.411, peakDb: -12, rmsDb: -23.4 },
    { file: '/audio/alive-happy-2.mp3', bytes: 22569, duration: 1.411, peakDb: -11.7, rmsDb: -23.6 },
  ],
  'alive.nuzzle': [
    { file: '/audio/alive-nuzzle-1.mp3', bytes: 19644, duration: 1.228, peakDb: -3.3, rmsDb: -23.5 },
    { file: '/audio/alive-nuzzle-2.mp3', bytes: 19644, duration: 1.228, peakDb: -6.3, rmsDb: -23.3 },
  ],
  'reward.sheets': [
    { file: '/audio/reward-sheets-1.mp3', bytes: 20480, duration: 1.28, peakDb: -1.6, rmsDb: -22.6 },
    { file: '/audio/reward-sheets-2.mp3', bytes: 18390, duration: 1.149, peakDb: -1.8, rmsDb: -21.7 },
  ],
  'reward.goldleaf': [
    { file: '/audio/reward-goldleaf-1.mp3', bytes: 26331, duration: 1.646, peakDb: -1.2, rmsDb: -25.2 },
    { file: '/audio/reward-goldleaf-2.mp3', bytes: 25495, duration: 1.593, peakDb: -1.4, rmsDb: -23.5 },
  ],
  'reward.mastery': [
    { file: '/audio/reward-mastery.mp3', bytes: 41377, duration: 2.586, peakDb: -6.5, rmsDb: -20.4 },
  ],
  'reward.unlock': [
    { file: '/audio/reward-unlock.mp3', bytes: 16300, duration: 1.019, peakDb: -1.9, rmsDb: -23.9 },
  ],
}

export const TEXTURES: Readonly<Record<TextureId, LoopAsset>> = {
  'texture.rub.slow':
    { file: '/audio/texture-rub-slow.mp3', bytes: 169691, duration: 10.606, peakDb: -1.3, rmsDb: -22.7, loopEnd: 10.576 },
  'texture.rub.fast':
    { file: '/audio/texture-rub-fast.mp3', bytes: 173453, duration: 10.841, peakDb: -1.6, rmsDb: -22.4, loopEnd: 10.8 },
  'texture.burnish':
    { file: '/audio/texture-burnish.mp3', bytes: 140434, duration: 8.777, peakDb: -1.7, rmsDb: -28.6, loopEnd: 8.75 },
  'texture.press.hold':
    { file: '/audio/texture-press-hold.mp3', bytes: 106161, duration: 6.635, peakDb: -1.4, rmsDb: -25.5, loopEnd: 6.59 },
}

export const AMBIENCE: Readonly<Record<Exclude<AmbienceId, 'none'>, LoopAsset>> = {
  'meadow':
    { file: '/audio/amb-meadow.mp3', bytes: 273554, duration: 19.54, peakDb: -11.7, rmsDb: -27.4, loopEnd: 19.5 },
  'rain':
    { file: '/audio/amb-rain.mp3', bytes: 273554, duration: 19.54, peakDb: -6.7, rmsDb: -27.5, loopEnd: 19.5 },
  'night':
    { file: '/audio/amb-night.mp3', bytes: 273554, duration: 19.54, peakDb: -10.8, rmsDb: -27.4, loopEnd: 19.5 },
  'shore':
    { file: '/audio/amb-shore.mp3', bytes: 272823, duration: 19.487, peakDb: -8, rmsDb: -27.9, loopEnd: 19.45 },
  'tearoom':
    { file: '/audio/amb-tearoom.mp3', bytes: 273554, duration: 19.54, peakDb: -6, rmsDb: -30.3, loopEnd: 19.5 },
}

/** Cues worth having decoded before the player's first gesture. */
export const PRELOAD_CORE: readonly SfxCue[] = [
  'ui.tap', 'ui.confirm', 'ui.back', 'crease.soft', 'crease.crisp', 'crease.set',
  'fold.valley', 'fold.mountain', 'sheet.slide', 'sheet.settle',
]

export const TOTAL_BYTES = 2979079
