// PAPER PLANET — measure every shipped asset. Writes tools/.cache/levels.json.
// Node only, never shipped.  Usage: node tools/measure-assets.mjs

import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { decodeMp3, toMono, peakOf, toDb } from './audio-lib.mjs'
import {
  integratedLufs, momentaryMaxLufs, shortTermMaxLufs, shortWindowLufs, ungatedLufs,
  loudnessRange, truePeakDb, selfTest,
} from './loudness.mjs'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const DIR = path.join(HERE, '..', 'app', 'public', 'audio')
const OUT = path.join(HERE, '.cache', 'levels.json')

const t = selfTest()
if (t.coeffErr > 1e-9 || t.sineErr > 0.05) throw new Error(`loudness meter failed self-test: ${JSON.stringify(t)}`)

const files = readdirSync(DIR).filter((f) => f.endsWith('.mp3')).sort()
const out = {}

for (const f of files) {
  const { sampleRate, channels } = await decodeMp3(readFileSync(path.join(DIR, f)))
  const pcm = toMono(channels)
  out[f] = {
    sampleRate,
    seconds: +(pcm.length / sampleRate).toFixed(3),
    lufsI: +integratedLufs(pcm, sampleRate).toFixed(2),
    lufsMmax: +momentaryMaxLufs(pcm, sampleRate).toFixed(2),
    lufs100: +shortWindowLufs(pcm, sampleRate).toFixed(2),
    lufsUngated: +ungatedLufs(pcm, sampleRate).toFixed(2),
    lufsSmax: +shortTermMaxLufs(pcm, sampleRate).toFixed(2),
    lra: +loudnessRange(pcm, sampleRate).toFixed(2),
    samplePeakDb: +toDb(peakOf(pcm)).toFixed(2),
    truePeakDb: +truePeakDb(pcm).toFixed(2),
  }
  process.stderr.write('.')
}
process.stderr.write('\n')

mkdirSync(path.dirname(OUT), { recursive: true })
writeFileSync(OUT, JSON.stringify(out, null, 1))
console.log(`measured ${files.length} assets -> ${path.relative(process.cwd(), OUT)}`)
console.log(`meter self-test: coeff err ${t.coeffErr.toExponential(2)}, −20 dBFS sine reads ${t.sineLufs.toFixed(3)} LUFS`)

/* ── emit the table the app ships with ─────────────────────────────────── */

const TS = path.join(HERE, '..', 'app', 'src', 'audio', 'levels.ts')
const rows = files.map((f) => {
  const v = out[f]
  return `  '/audio/${f}': { l100: ${v.lufs100}, li: ${v.lufsI}, ls: ${v.lufsSmax}, lu: ${v.lufsUngated}, tp: ${v.truePeakDb} },`
}).join('\n')

writeFileSync(TS, `// PAPER PLANET — GENERATED by tools/measure-assets.mjs. Do not edit by hand.
//
// What every shipped file actually measures, so the mix in ./mix.ts can be
// written as targets rather than as guessed numbers. All figures are ITU-R
// BS.1770-4 K-weighted, taken from the mono file — the graph's mono-to-stereo
// upmix adds the same +3 LU to every one of them, so it cancels in every
// comparison the mix makes.
//
//   l100  loudest 100 ms window. The statistic for one-shots: a crease snap is
//         40 ms of event inside a one-second file, and the standard 400 ms
//         window reads it 5-8 LU quieter than it sounds.
//   li    gated integrated loudness. The statistic for a bed you live with.
//   ls    loudest 3 s window — a bed's loudest sustained passage.
//   lu    ungated K-weighted level of the whole file. The statistic for a
//         granular source, where a grain lands anywhere with equal chance.
//   tp    true peak, 4x oversampled, dBTP.

/** Measured level of one shipped file. Every figure is dB or LUFS. */
export interface MeasuredLevel {
  readonly l100: number
  readonly li: number
  readonly ls: number
  readonly lu: number
  readonly tp: number
}

export const LEVELS: Readonly<Record<string, MeasuredLevel>> = {
${rows}
}
`)
console.log(`wrote ${path.relative(process.cwd(), TS)}`)
